export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGIST = 'regist'
export const FETCH_USER_INFO = 'fetchUserInfo'
export const CHANGE_EMAIL = 'changeEmail'
export const FETCH_PERMISSION = 'fetchPermission'
export const CLEAR_PERMISSION = 'clearPermission'
export const FETCH_SYSTEM_PROP = 'fetchSystemProp'
